//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HSSNInventoryEntities : DbContext
    {
        public HSSNInventoryEntities()
            : base("name=HSSNInventoryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BillOfMaterial> BillOfMaterials { get; set; }
        public DbSet<BillOfMaterialDetail> BillOfMaterialDetails { get; set; }
        public DbSet<Brand> Brands { get; set; }
        public DbSet<Dealer> Dealers { get; set; }
        public DbSet<DispatchOrder> DispatchOrders { get; set; }
        public DbSet<DispatchOrderDetail> DispatchOrderDetails { get; set; }
        public DbSet<FinanceDispatch> FinanceDispatches { get; set; }
        public DbSet<FinanceDispatchDetail> FinanceDispatchDetails { get; set; }
        public DbSet<Flavour> Flavours { get; set; }
        public DbSet<FormModule> FormModules { get; set; }
        public DbSet<GoodReceivedNote> GoodReceivedNotes { get; set; }
        public DbSet<GrnDetail> GrnDetails { get; set; }
        public DbSet<Invoice> Invoices { get; set; }
        public DbSet<InvoiceDetail> InvoiceDetails { get; set; }
        public DbSet<IssueMaterial> IssueMaterials { get; set; }
        public DbSet<IssueProductMaterialDetail> IssueProductMaterialDetails { get; set; }
        public DbSet<JobOrder> JobOrders { get; set; }
        public DbSet<JobOrderDetail> JobOrderDetails { get; set; }
        public DbSet<Organisation> Organisations { get; set; }
        public DbSet<PRNDetail> PRNDetails { get; set; }
        public DbSet<Product> Products { get; set; }
        public DbSet<ProductionMaterial> ProductionMaterials { get; set; }
        public DbSet<ProductionMaterialLedger> ProductionMaterialLedgers { get; set; }
        public DbSet<ProductLedger> ProductLedgers { get; set; }
        public DbSet<ProductNormTemplate> ProductNormTemplates { get; set; }
        public DbSet<ProductNormTemplateDetail> ProductNormTemplateDetails { get; set; }
        public DbSet<ProductStock> ProductStocks { get; set; }
        public DbSet<PurchaseRequisitionNote> PurchaseRequisitionNotes { get; set; }
        public DbSet<Region> Regions { get; set; }
        public DbSet<SerialNumber> SerialNumbers { get; set; }
        public DbSet<SubCategory> SubCategories { get; set; }
        public DbSet<SubProduct> SubProducts { get; set; }
        public DbSet<UnitOfMeasurement> UnitOfMeasurements { get; set; }
        public DbSet<UserDetail> UserDetails { get; set; }
        public DbSet<UserProfile> UserProfiles { get; set; }
        public DbSet<UserProfileDetail> UserProfileDetails { get; set; }
        public DbSet<WareHouse> WareHouses { get; set; }
    }
}
