//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillOfMaterial
    {
        public int BillOfMaterialId { get; set; }
        public string BillOfmaterialCode { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> BatchQuantity { get; set; }
        public Nullable<int> CartoonQuantity { get; set; }
        public Nullable<byte> IsIssued { get; set; }
        public Nullable<System.DateTime> PreparedDate { get; set; }
        public Nullable<int> PreparedBy { get; set; }
    }
}
