//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillOfMaterialDetail
    {
        public int BillOfMaterialDetailId { get; set; }
        public int BillOfMaterialId { get; set; }
        public int ProductMaterialId { get; set; }
        public int UnitOfMeasurement { get; set; }
        public int ManufacturedProductId { get; set; }
        public decimal Quantity { get; set; }
    }
}
