//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dealer
    {
        public int DealerId { get; set; }
        public string DealerName { get; set; }
        public string DealerAddress { get; set; }
        public string PhoneNo { get; set; }
        public string MobileNo { get; set; }
        public string Email { get; set; }
        public int RegionId { get; set; }
        public string DelearIncharge { get; set; }
        public Nullable<byte> IsSupplier { get; set; }
    }
}
