//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinanceDispatchDetail
    {
        public int FinanceDispatchDetailId { get; set; }
        public int FinanceDispatchId { get; set; }
        public int DispatchOrderId { get; set; }
        public int ProductId { get; set; }
        public int DispatchFromWareHouseId { get; set; }
        public decimal Quantity { get; set; }
        public Nullable<decimal> ExcessShortageQuantity { get; set; }
        public Nullable<int> UnitOfMeasurementId { get; set; }
        public decimal Rate { get; set; }
    }
}
