//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class GrnDetail
    {
        public int GrnDetailId { get; set; }
        public int GoodReceivedNoteId { get; set; }
        public int ProductionMaterialId { get; set; }
        public decimal OrderQuantity { get; set; }
        public decimal ReceivedQuantity { get; set; }
    }
}
