//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class IssueMaterial
    {
        public int IssueProductMaterilId { get; set; }
        public Nullable<int> Issuedcode { get; set; }
        public Nullable<int> Issuedby { get; set; }
        public Nullable<int> BillOfMaterialId { get; set; }
        public Nullable<System.DateTime> IssueDateTime { get; set; }
        public Nullable<int> ReturnBy { get; set; }
        public Nullable<System.DateTime> ReturnDatetimer { get; set; }
        public Nullable<int> IssueReceivedBy { get; set; }
        public Nullable<int> ReturnReceivedBy { get; set; }
        public string IssueRemarks { get; set; }
        public string ReturnRemarks { get; set; }
    }
}
