//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductNormTemplate
    {
        public ProductNormTemplate()
        {
            this.ProductNormTemplateDetails = new HashSet<ProductNormTemplateDetail>();
        }
    
        public int ProductNormTemplateId { get; set; }
        public int ProductId { get; set; }
        public decimal OutputQuantity { get; set; }
        public decimal WasteQuantity { get; set; }
        public int PreparedBy { get; set; }
        public System.DateTime PreparedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual ICollection<ProductNormTemplateDetail> ProductNormTemplateDetails { get; set; }
    }
}
