//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductionMaterial
    {
        public ProductionMaterial()
        {
            this.ProductNormTemplateDetails = new HashSet<ProductNormTemplateDetail>();
        }
    
        public int ProductionMaterialId { get; set; }
        public string MaterialName { get; set; }
        public int UnitOfMeasurementId { get; set; }
        public string MaterialType { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<ProductNormTemplateDetail> ProductNormTemplateDetails { get; set; }
    }
}
