//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ProductId { get; set; }
        public Nullable<int> BrandId { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> FlavourId { get; set; }
        public string SKUCode { get; set; }
        public double weight { get; set; }
        public int UnitOfMeasureId { get; set; }
        public int PacketPerCartoon { get; set; }
        public decimal PerCartoonRate { get; set; }
        public byte IsVat { get; set; }
        public byte ExerciseDuty { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
