//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseRequisitionNote
    {
        public int PurchaseRequisitionNoteId { get; set; }
        public int PrnNumber { get; set; }
        public System.DateTime EngPRNDate { get; set; }
        public string NepPRNDate { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string Reason { get; set; }
        public Nullable<byte> IsApprovedByGM { get; set; }
        public Nullable<int> ApproverId { get; set; }
        public Nullable<System.DateTime> DateOfApproved { get; set; }
    }
}
